version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: ems-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ems
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: